#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/ms-qr1-prestart-provision.sh prestart-init
  scripts/ms-qr1-prestart-provision.sh check
  scripts/ms-qr1-prestart-provision.sh n8n-user
  scripts/ms-qr1-prestart-provision.sh writer-services
  scripts/ms-qr1-prestart-provision.sh writer-containers
  scripts/ms-qr1-prestart-provision.sh verify-quiescent
  scripts/ms-qr1-prestart-provision.sh poststart-refresh

Idempotently prepares QR1 bind-mount prerequisites before any Docker Compose
up/create action:
  - data/persona/SOUL.md generated by scripts/build-installation-context.py
  - data/n8n owned and writable by the effective n8n container UID:GID

Run from the ods/ directory after .env is filled enough for QR1 Compose render.
USAGE
}

ACTION="${1:-prestart-init}"
case "$ACTION" in
  prestart-init|provision|check|n8n-user|writer-services|writer-containers|verify-quiescent|poststart-refresh) ;;
  -h|--help|help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac
[[ "$ACTION" == "provision" ]] && ACTION="prestart-init"

require() {
  command -v "$1" >/dev/null || { echo "ERROR: $1 is required" >&2; exit 1; }
}

if [[ ! -x scripts/ms-qr1-compose-flags.sh || ! -f scripts/build-installation-context.py ]]; then
  echo "ERROR: run from the ods/ directory" >&2
  exit 1
fi

require python3

DEPLOY_UID="${MS_QR1_DEPLOY_UID:-${SUDO_UID:-$(id -u)}}"
DEPLOY_GID="${MS_QR1_DEPLOY_GID:-${SUDO_GID:-$(id -g)}}"
DATA_DIR="${MS_QR1_DATA_DIR:-data}"
LANGFUSE_DIR="$DATA_DIR/langfuse"
PERSONA_DIR="$DATA_DIR/persona"
SOUL_PATH="$PERSONA_DIR/SOUL.md"
N8N_DIR="$DATA_DIR/n8n"
HERMES_HEALTH_TIMEOUT="${MS_QR1_HERMES_HEALTH_TIMEOUT:-120}"
HERMES_HEALTH_INTERVAL="${MS_QR1_HERMES_HEALTH_INTERVAL:-2}"

is_root() {
  [[ "$(id -u)" -eq 0 ]]
}

require_root() {
  echo "ERROR: $1" >&2
  echo "Rerun this specific QR1 provisioning step with sudo; do not continue to Compose first." >&2
  exit 1
}

compose_json() {
  require docker
  MS_QR1_HOST_GATEWAY="${MS_QR1_HOST_GATEWAY:-127.0.0.1}" \
    docker compose $(scripts/ms-qr1-compose-flags.sh) config --format json
}

writers_for_data_targets() {
  local output_kind="$1" rendered data_abs
  rendered="$(compose_json)"
  data_abs="$(python3 - "$DATA_DIR" <<'PY'
from pathlib import Path
import sys

print(Path(sys.argv[1]).resolve())
PY
)"
  COMPOSE_JSON="$rendered" DATA_ABS="$data_abs" OUTPUT_KIND="$output_kind" python3 - <<'PY'
import json
import os
from pathlib import Path

data = json.loads(os.environ["COMPOSE_JSON"])
data_abs = Path(os.environ["DATA_ABS"]).resolve()
output_kind = os.environ["OUTPUT_KIND"]
targets = [
    (data_abs / "n8n").resolve(),
    (data_abs / "persona").resolve(),
    (data_abs / "langfuse").resolve(),
]
writers = []

def contains_or_is_contained(left: Path, right: Path) -> bool:
    return left == right or left in right.parents or right in left.parents

for service_name, service in sorted(data.get("services", {}).items()):
    for volume in service.get("volumes") or []:
        source = None
        read_only = False
        if isinstance(volume, str):
            parts = volume.split(":")
            if len(parts) >= 2:
                source = parts[0]
                read_only = "ro" in parts[2:]
        elif isinstance(volume, dict) and volume.get("type") == "bind":
            source = volume.get("source")
            read_only = bool(volume.get("read_only"))
        if not source or read_only:
            continue
        source_path = Path(source)
        if not source_path.is_absolute():
            parts = source_path.parts
            if parts and parts[0] in {".", "data"}:
                parts = tuple(part for part in parts if part != ".")
            if parts and parts[0] == "data":
                source_path = data_abs.joinpath(*parts[1:])
            else:
                source_path = Path.cwd() / source_path
        try:
            source_abs = source_path.resolve()
        except FileNotFoundError:
            source_abs = source_path.absolute()
        if any(contains_or_is_contained(source_abs, target) for target in targets):
            if output_kind == "services":
                writers.append(service_name)
            else:
                writers.append(str(service.get("container_name") or f"ods-{service_name}"))
            break

for name in sorted(set(writers)):
    print(name)
PY
}

writer_services_for_data_targets() {
  writers_for_data_targets services
}

writer_containers_for_data_targets() {
  writers_for_data_targets containers
}

require_quiescent_data_writers() {
  # ADR: docs/ms/decisions/QR1-QUIESCENT-PRIVILEGED-PROVISIONING.md.
  # Privileged repair is only allowed while containers that can write the
  # affected persistent data paths are stopped; runtime checks stay read-only.
  require docker
  local expected running active
  expected="$(writer_containers_for_data_targets)"
  [[ -n "$expected" ]] || return 0
  running="$(docker ps --format '{{.Names}}')"
  active="$(EXPECTED_WRITERS="$expected" RUNNING_CONTAINERS="$running" python3 - <<'PY'
import os

expected = set(filter(None, os.environ["EXPECTED_WRITERS"].splitlines()))
running = set(filter(None, os.environ["RUNNING_CONTAINERS"].splitlines()))
for name in sorted(expected & running):
    print(name)
PY
)"
  if [[ -n "$active" ]]; then
    echo "ERROR: privileged QR1 prestart-init requires quiescent container-writable state." >&2
    echo "Stop these writer container(s) before repair:" >&2
    printf '  %s\n' $active >&2
    echo "Run: docker stop $(printf '%s\n' "$active" | tr '\n' ' ')" >&2
    return 1
  fi
}

wait_for_hermes_healthy() {
  local deadline status health
  deadline=$((SECONDS + HERMES_HEALTH_TIMEOUT))
  while (( SECONDS <= deadline )); do
    if ! status="$(docker inspect --format '{{.State.Status}} {{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' ods-hermes)"; then
      echo "ERROR: cannot inspect ods-hermes health" >&2
      return 1
    fi
    health="${status#* }"
    status="${status%% *}"
    case "$status:$health" in
      running:healthy)
        return 0
        ;;
      exited:*|dead:*|*:unhealthy)
        echo "ERROR: ods-hermes reached non-healthy state: status=$status health=$health" >&2
        return 1
        ;;
    esac
    sleep "$HERMES_HEALTH_INTERVAL"
  done
  echo "ERROR: timed out waiting for ods-hermes health=healthy" >&2
  return 1
}

resolve_n8n_user() {
  local rendered
  rendered="$(compose_json)"
  COMPOSE_JSON="$rendered" python3 - <<'PY'
import json
import os
import re
import sys

data = json.loads(os.environ["COMPOSE_JSON"])
services = data.get("services", {})
if "n8n" not in services:
    sys.exit(0)
user = str(services.get("n8n", {}).get("user", "")).strip()
match = re.fullmatch(r"([0-9]+):([0-9]+)", user)
if not match:
    print(f"ERROR: rendered n8n user must be numeric UID:GID, got {user!r}", file=sys.stderr)
    sys.exit(1)
print(f"{match.group(1)}:{match.group(2)}")
PY
}

path_owner_mode() {
  python3 - "$1" <<'PY'
import os
import stat
import sys

st = os.lstat(sys.argv[1])
print(f"{st.st_uid}:{st.st_gid}:{stat.S_IMODE(st.st_mode):04o}")
PY
}

reject_symlink() {
  local path="$1"
  if [[ -L "$path" ]]; then
    echo "ERROR: $path is a symlink; refusing privileged QR1 provisioning" >&2
    return 1
  fi
}

validate_persona_paths() {
  reject_symlink "$PERSONA_DIR"
  reject_symlink "$SOUL_PATH"
  [[ -d "$PERSONA_DIR" ]] || { echo "ERROR: missing $PERSONA_DIR" >&2; return 1; }
  [[ -f "$SOUL_PATH" ]] || { echo "ERROR: missing regular $SOUL_PATH" >&2; return 1; }
}

ensure_persona() {
  reject_symlink "$PERSONA_DIR"
  reject_symlink "$SOUL_PATH"
  mkdir -p "$PERSONA_DIR"
  reject_symlink "$PERSONA_DIR"
  reject_symlink "$SOUL_PATH"
  local persona_owner
  persona_owner="$(path_owner_mode "$PERSONA_DIR")"
  if [[ "$persona_owner" != "$DEPLOY_UID:$DEPLOY_GID:"* ]]; then
    if [[ "$ACTION" == "poststart-refresh" ]]; then
      echo "ERROR: $PERSONA_DIR owner is $persona_owner, expected $DEPLOY_UID:$DEPLOY_GID" >&2
      echo "Post-start refresh is intentionally unprivileged; stop the stack and rerun prestart-init with sudo if repair is required." >&2
      return 1
    fi
    is_root || require_root "$PERSONA_DIR owner is $persona_owner, expected $DEPLOY_UID:$DEPLOY_GID"
    chown "$DEPLOY_UID:$DEPLOY_GID" "$PERSONA_DIR"
  fi
  reject_symlink "$SOUL_PATH"
  if [[ -d "$SOUL_PATH" ]]; then
    if [[ "$ACTION" != "prestart-init" ]]; then
      echo "ERROR: $SOUL_PATH is a directory, probably created by a previous failed Docker bind mount." >&2
      echo "Run prestart-init after verifying writer containers are stopped." >&2
      return 1
    fi
    # ADR: accidental Docker-created SOUL.md directories are repaired only
    # after prestart-init has verified quiescent writers.
    rmdir "$SOUL_PATH" || {
      echo "ERROR: $SOUL_PATH is a non-empty directory; refusing automatic repair." >&2
      return 1
    }
  fi
  reject_symlink "$SOUL_PATH"
  local soul_tmp
  # Build to a same-directory temp file and atomically replace SOUL.md so
  # Hermes never observes a partial persona and bind-mount creation sees a file.
  soul_tmp="$(mktemp "$PERSONA_DIR/.SOUL.md.tmp.XXXXXX")"
  trap 'rm -f "$soul_tmp"' RETURN
  python3 scripts/build-installation-context.py --output "$soul_tmp"
  if [[ ! -f "$soul_tmp" || -L "$soul_tmp" ]]; then
    echo "ERROR: persona builder did not generate a regular temporary file" >&2
    return 1
  fi
  python3 - "$soul_tmp" <<'PY'
from pathlib import Path
import sys

Path(sys.argv[1]).read_text(encoding="utf-8")
PY
  PERSONA_DIR="$PERSONA_DIR" SOUL_TMP="$soul_tmp" DEPLOY_UID="$DEPLOY_UID" DEPLOY_GID="$DEPLOY_GID" python3 - <<'PY'
import errno
import os
import stat
import sys

persona_dir = os.environ["PERSONA_DIR"]
soul_tmp = os.environ["SOUL_TMP"]
deploy_uid = int(os.environ["DEPLOY_UID"])
deploy_gid = int(os.environ["DEPLOY_GID"])
open_flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
dir_flags = open_flags | getattr(os, "O_DIRECTORY", 0)

def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)

try:
    tmp_st = os.lstat(soul_tmp)
except FileNotFoundError:
    fail(f"missing generated temporary persona file {soul_tmp}")
if stat.S_ISLNK(tmp_st.st_mode) or not stat.S_ISREG(tmp_st.st_mode):
    fail(f"{soul_tmp} is not a regular generated persona file")

try:
    persona_fd = os.open(persona_dir, dir_flags)
except OSError as exc:
    if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
        fail(f"{persona_dir} is a symlink; refusing privileged QR1 provisioning")
    fail(f"cannot open {persona_dir} safely: {exc.strerror}")
try:
    persona_st = os.fstat(persona_fd)
    if not stat.S_ISDIR(persona_st.st_mode):
        fail(f"{persona_dir} is not a directory")
    try:
        existing = os.stat("SOUL.md", dir_fd=persona_fd, follow_symlinks=False)
    except FileNotFoundError:
        existing = None
    if existing is not None:
        if stat.S_ISLNK(existing.st_mode):
            fail(f"{persona_dir}/SOUL.md is a symlink; refusing privileged QR1 provisioning")
        if stat.S_ISDIR(existing.st_mode):
            fail(f"{persona_dir}/SOUL.md is a directory, probably created by a previous failed Docker bind mount.")
        if not stat.S_ISREG(existing.st_mode):
            fail(f"{persona_dir}/SOUL.md is not a regular file")
    if os.geteuid() == 0:
        os.chown(soul_tmp, deploy_uid, deploy_gid, follow_symlinks=False)
    os.chmod(soul_tmp, 0o644, follow_symlinks=False)
    os.rename(soul_tmp, "SOUL.md", dst_dir_fd=persona_fd)
    final_st = os.stat("SOUL.md", dir_fd=persona_fd, follow_symlinks=False)
    if stat.S_ISLNK(final_st.st_mode) or not stat.S_ISREG(final_st.st_mode):
        fail(f"{persona_dir}/SOUL.md was not installed as a regular file")
finally:
    os.close(persona_fd)
PY
  rm -f "$soul_tmp"
  trap - RETURN
}

validate_or_normalize_n8n_tree() {
  N8N_DIR="$N8N_DIR" N8N_UID="$1" N8N_GID="$2" N8N_NORMALIZE="${3:-0}" python3 - <<'PY'
import errno
import os
import stat
import sys

root = os.environ["N8N_DIR"]
expected_uid = int(os.environ["N8N_UID"])
expected_gid = int(os.environ["N8N_GID"])
normalize = os.environ["N8N_NORMALIZE"] == "1"
force_chmod_not_implemented = os.environ.get("MS_QR1_TEST_CHMOD_NO_FOLLOW_UNSUPPORTED") == "1"
running_as_root = os.geteuid() == 0
open_flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
dir_flags = open_flags | getattr(os, "O_DIRECTORY", 0)

def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)

def desired_mode(path: str, st: os.stat_result) -> int:
    mode = stat.S_IMODE(st.st_mode)
    if stat.S_ISDIR(st.st_mode):
        return 0o700
    if stat.S_ISREG(st.st_mode):
        return 0o600 | (mode & stat.S_IXUSR)
    fail(f"{path} is neither a directory nor a regular file")

def apply_or_check(fd: int, display: str, st: os.stat_result) -> None:
    desired = desired_mode(display, st)
    if (st.st_uid, st.st_gid) != (expected_uid, expected_gid):
        if not normalize or not running_as_root:
            fail(f"{display} owner is {st.st_uid}:{st.st_gid}, expected {expected_uid}:{expected_gid}")
        os.fchown(fd, expected_uid, expected_gid)
        st = os.fstat(fd)
    mode = stat.S_IMODE(st.st_mode)
    if normalize and mode != desired:
        try:
            if force_chmod_not_implemented:
                raise NotImplementedError("forced test path")
            os.fchmod(fd, desired)
        except NotImplementedError:
            fail(f"cannot chmod {display} without following symlinks on this Python/platform; use Ubuntu 24.04 or a Python build with follow_symlinks support")
        except PermissionError:
            fail(f"cannot chmod {display}; rerun provisioning with sudo")
        mode = stat.S_IMODE(os.fstat(fd).st_mode)
    if not normalize:
        if not mode & stat.S_IWUSR:
            fail(f"{display} is not owner-writable: {mode:04o}")
        if stat.S_ISDIR(st.st_mode) and not mode & stat.S_IXUSR:
            fail(f"{display} is not owner-searchable: {mode:04o}")
        if mode & stat.S_IWGRP:
            fail(f"{display} is group-writable: {mode:04o}")
        if mode & stat.S_IWOTH:
            fail(f"{display} is world-writable: {mode:04o}")
    elif mode != desired:
        fail(f"{display} mode is {mode:04o}, expected {desired:04o}")

def open_child(parent_fd: int, parent_display: str, name: str) -> tuple[int, os.stat_result]:
    display = os.path.join(parent_display, name)
    try:
        st = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        fail(f"{display} disappeared during traversal")
    if stat.S_ISLNK(st.st_mode):
        fail(f"{display} is a symlink; refusing privileged n8n provisioning")
    if not stat.S_ISDIR(st.st_mode) and not stat.S_ISREG(st.st_mode):
        fail(f"{display} is neither a directory nor a regular file")
    if not normalize and stat.S_ISDIR(st.st_mode):
        mode = stat.S_IMODE(st.st_mode)
        if (st.st_uid, st.st_gid) != (expected_uid, expected_gid):
            fail(f"{display} owner is {st.st_uid}:{st.st_gid}, expected {expected_uid}:{expected_gid}")
        if not mode & stat.S_IWUSR:
            fail(f"{display} is not owner-writable: {mode:04o}")
        if not mode & stat.S_IXUSR:
            fail(f"{display} is not owner-searchable: {mode:04o}")
        if mode & stat.S_IWGRP:
            fail(f"{display} is group-writable: {mode:04o}")
        if mode & stat.S_IWOTH:
            fail(f"{display} is world-writable: {mode:04o}")
    flags = dir_flags if stat.S_ISDIR(st.st_mode) else open_flags
    try:
        child_fd = os.open(name, flags, dir_fd=parent_fd)
    except OSError as exc:
        if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
            fail(f"{display} changed during traversal or is a symlink")
        if exc.errno == errno.ENOENT:
            fail(f"{display} disappeared during traversal")
        fail(f"cannot open {display} safely: {exc.strerror}")
    opened_st = os.fstat(child_fd)
    return child_fd, opened_st

def visit_dir(dir_fd: int, display: str, st: os.stat_result) -> None:
    if not stat.S_ISDIR(st.st_mode):
        fail(f"{display} is not a directory")
    apply_or_check(dir_fd, display, st)
    try:
        names = sorted(os.listdir(dir_fd))
    except OSError as exc:
        fail(f"cannot list {display}: {exc.strerror}")
    for name in names:
        if name in {"", ".", ".."} or "/" in name or "\0" in name:
            fail(f"{display} contains invalid entry name {name!r}")
        child_fd, child_st = open_child(dir_fd, display, name)
        try:
            child_display = os.path.join(display, name)
            if stat.S_ISDIR(child_st.st_mode):
                visit_dir(child_fd, child_display, child_st)
            elif stat.S_ISREG(child_st.st_mode):
                apply_or_check(child_fd, child_display, child_st)
            else:
                fail(f"{child_display} is neither a directory nor a regular file")
        finally:
            os.close(child_fd)

try:
    root_fd = os.open(root, dir_flags)
except FileNotFoundError:
    fail(f"missing {root}")
except OSError as exc:
    if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
        fail(f"{root} is a symlink; refusing privileged n8n provisioning")
    fail(f"cannot open {root} safely: {exc.strerror}")
try:
    root_st = os.fstat(root_fd)
    visit_dir(root_fd, root, root_st)
finally:
    os.close(root_fd)
PY
}

ensure_n8n_dir() {
  local n8n_user n8n_uid n8n_gid
  n8n_user="$(resolve_n8n_user)"
  if [[ -z "$n8n_user" ]]; then
    echo "QR1 n8n service absent from rendered stack; skipping data/n8n provisioning"
    return 0
  fi
  n8n_uid="${n8n_user%%:*}"
  n8n_gid="${n8n_user##*:}"
  mkdir -p "$N8N_DIR"
  if ! validate_or_normalize_n8n_tree "$n8n_uid" "$n8n_gid" 1; then
    is_root || require_root "$N8N_DIR requires ownership or mode repair for $n8n_uid:$n8n_gid"
    return 1
  fi
  validate_or_normalize_n8n_tree "$n8n_uid" "$n8n_gid" 0
}

check_prestart() {
  validate_persona_paths
  python3 - "$SOUL_PATH" <<'PY'
from pathlib import Path
import sys

Path(sys.argv[1]).read_text(encoding="utf-8")
PY
  local n8n_user n8n_uid n8n_gid
  n8n_user="$(resolve_n8n_user)"
  if [[ -z "$n8n_user" ]]; then
    return 0
  fi
  [[ -d "$N8N_DIR" ]] || { echo "ERROR: missing $N8N_DIR" >&2; return 1; }
  n8n_uid="${n8n_user%%:*}"
  n8n_gid="${n8n_user##*:}"
  validate_or_normalize_n8n_tree "$n8n_uid" "$n8n_gid" 0
}

if [[ "$ACTION" == "n8n-user" ]]; then
  resolve_n8n_user
  exit 0
fi

if [[ "$ACTION" == "writer-services" ]]; then
  writer_services_for_data_targets
  exit 0
fi

if [[ "$ACTION" == "writer-containers" ]]; then
  writer_containers_for_data_targets
  exit 0
fi

if [[ "$ACTION" == "verify-quiescent" ]]; then
  require_quiescent_data_writers
  exit 0
fi

if [[ "$ACTION" == "check" ]]; then
  check_prestart
  exit 0
fi

poststart_refresh() {
  if is_root; then
    echo "ERROR: poststart-refresh must run as the deployment user, not root." >&2
    echo "It refreshes deployment-user-owned persona state and must not perform privileged filesystem repair." >&2
    return 1
  fi
  # Same-directory atomic replacement changes SOUL.md's inode. Recreate Hermes
  # so Docker establishes a fresh file bind mount for the updated persona.
  ensure_persona
  require docker
  local containers
  containers="$(docker ps --format '{{.Names}}')"
  if ! grep -Fx 'ods-hermes' <<<"$containers" >/dev/null; then
    echo "ERROR: ods-hermes is not running; cannot refresh Hermes persona" >&2
    return 1
  fi
  # Recreate before copying so /opt/hermes/docker/SOUL.md is bound to the new
  # host inode; then sync the repository-supported persistent persona path.
  docker compose $(scripts/ms-qr1-compose-flags.sh) up -d --no-deps --force-recreate hermes
  wait_for_hermes_healthy
  docker exec ods-hermes cp /opt/hermes/docker/SOUL.md /opt/data/SOUL.md
  docker compose $(scripts/ms-qr1-compose-flags.sh) restart hermes
  wait_for_hermes_healthy
  docker compose $(scripts/ms-qr1-compose-flags.sh) up -d --no-deps --force-recreate hermes-proxy
}

if [[ "$ACTION" == "poststart-refresh" ]]; then
  poststart_refresh
  exit 0
fi

require_quiescent_data_writers
ensure_persona
ensure_n8n_dir
check_prestart
echo "QR1 pre-start provisioning complete"
