#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/ms-qr1-prestart-provision.sh
  scripts/ms-qr1-prestart-provision.sh check
  scripts/ms-qr1-prestart-provision.sh n8n-user
  scripts/ms-qr1-prestart-provision.sh poststart-refresh

Idempotently prepares QR1 bind-mount prerequisites before any Docker Compose
up/create action:
  - data/persona/SOUL.md generated by scripts/build-installation-context.py
  - data/n8n owned and writable by the effective n8n container UID:GID

Run from the ods/ directory after .env is filled enough for QR1 Compose render.
USAGE
}

ACTION="${1:-provision}"
case "$ACTION" in
  provision|check|n8n-user|poststart-refresh) ;;
  -h|--help|help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac

require() {
  command -v "$1" >/dev/null || { echo "ERROR: $1 is required" >&2; exit 1; }
}

if [[ ! -x scripts/ms-qr1-compose-flags.sh || ! -f scripts/build-installation-context.py ]]; then
  echo "ERROR: run from the ods/ directory" >&2
  exit 1
fi

require python3

DEPLOY_UID="${MS_QR1_DEPLOY_UID:-${SUDO_UID:-$(id -u)}}"
DEPLOY_GID="${MS_QR1_DEPLOY_GID:-${SUDO_GID:-$(id -g)}}"
DATA_DIR="${MS_QR1_DATA_DIR:-data}"
PERSONA_DIR="$DATA_DIR/persona"
SOUL_PATH="$PERSONA_DIR/SOUL.md"
N8N_DIR="$DATA_DIR/n8n"

is_root() {
  [[ "$(id -u)" -eq 0 ]]
}

require_root() {
  echo "ERROR: $1" >&2
  echo "Rerun this specific QR1 provisioning step with sudo; do not continue to Compose first." >&2
  exit 1
}

compose_json() {
  require docker
  MS_QR1_HOST_GATEWAY="${MS_QR1_HOST_GATEWAY:-127.0.0.1}" \
    docker compose $(scripts/ms-qr1-compose-flags.sh) config --format json
}

resolve_n8n_user() {
  local rendered
  rendered="$(compose_json)"
  COMPOSE_JSON="$rendered" python3 - <<'PY'
import json
import os
import re
import sys

data = json.loads(os.environ["COMPOSE_JSON"])
services = data.get("services", {})
if "n8n" not in services:
    sys.exit(0)
user = str(services.get("n8n", {}).get("user", "")).strip()
match = re.fullmatch(r"([0-9]+):([0-9]+)", user)
if not match:
    print(f"ERROR: rendered n8n user must be numeric UID:GID, got {user!r}", file=sys.stderr)
    sys.exit(1)
print(f"{match.group(1)}:{match.group(2)}")
PY
}

path_owner_mode() {
  python3 - "$1" <<'PY'
import os
import stat
import sys

st = os.lstat(sys.argv[1])
print(f"{st.st_uid}:{st.st_gid}:{stat.S_IMODE(st.st_mode):04o}")
PY
}

reject_symlink() {
  local path="$1"
  if [[ -L "$path" ]]; then
    echo "ERROR: $path is a symlink; refusing privileged QR1 provisioning" >&2
    return 1
  fi
}

validate_persona_paths() {
  reject_symlink "$PERSONA_DIR"
  reject_symlink "$SOUL_PATH"
  [[ -d "$PERSONA_DIR" ]] || { echo "ERROR: missing $PERSONA_DIR" >&2; return 1; }
  [[ -f "$SOUL_PATH" ]] || { echo "ERROR: missing regular $SOUL_PATH" >&2; return 1; }
}

ensure_persona() {
  reject_symlink "$PERSONA_DIR"
  reject_symlink "$SOUL_PATH"
  mkdir -p "$PERSONA_DIR"
  reject_symlink "$PERSONA_DIR"
  reject_symlink "$SOUL_PATH"
  local persona_owner
  persona_owner="$(path_owner_mode "$PERSONA_DIR")"
  if [[ "$persona_owner" != "$DEPLOY_UID:$DEPLOY_GID:"* ]]; then
    is_root || require_root "$PERSONA_DIR owner is $persona_owner, expected $DEPLOY_UID:$DEPLOY_GID"
    chown "$DEPLOY_UID:$DEPLOY_GID" "$PERSONA_DIR"
  fi
  reject_symlink "$SOUL_PATH"
  if [[ -d "$SOUL_PATH" ]]; then
    echo "ERROR: $SOUL_PATH is a directory, probably created by a previous failed Docker bind mount." >&2
    echo "Remove the directory, restore $PERSONA_DIR ownership, and rerun this helper before Compose." >&2
    return 1
  fi
  reject_symlink "$SOUL_PATH"
  local soul_tmp
  soul_tmp="$(mktemp "${TMPDIR:-/tmp}/ms-qr1-soul.XXXXXX")"
  trap 'rm -f "$soul_tmp"' RETURN
  python3 scripts/build-installation-context.py --output "$soul_tmp"
  if [[ ! -f "$soul_tmp" || -L "$soul_tmp" ]]; then
    echo "ERROR: persona builder did not generate a regular temporary file" >&2
    return 1
  fi
  python3 - "$soul_tmp" <<'PY'
from pathlib import Path
import sys

Path(sys.argv[1]).read_text(encoding="utf-8")
PY
  PERSONA_DIR="$PERSONA_DIR" SOUL_TMP="$soul_tmp" DEPLOY_UID="$DEPLOY_UID" DEPLOY_GID="$DEPLOY_GID" python3 - <<'PY'
import errno
import os
import stat
import sys

persona_dir = os.environ["PERSONA_DIR"]
soul_tmp = os.environ["SOUL_TMP"]
deploy_uid = int(os.environ["DEPLOY_UID"])
deploy_gid = int(os.environ["DEPLOY_GID"])
race_mode = os.environ.get("MS_QR1_TEST_PERSONA_RACE", "")
race_external = os.environ.get("MS_QR1_TEST_PERSONA_RACE_EXTERNAL", "")
open_flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
dir_flags = open_flags | getattr(os, "O_DIRECTORY", 0)

def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)

try:
    tmp_st = os.lstat(soul_tmp)
except FileNotFoundError:
    fail(f"missing generated temporary persona file {soul_tmp}")
if stat.S_ISLNK(tmp_st.st_mode) or not stat.S_ISREG(tmp_st.st_mode):
    fail(f"{soul_tmp} is not a regular generated persona file")

try:
    persona_fd = os.open(persona_dir, dir_flags)
except OSError as exc:
    if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
        fail(f"{persona_dir} is a symlink; refusing privileged QR1 provisioning")
    fail(f"cannot open {persona_dir} safely: {exc.strerror}")
try:
    persona_st = os.fstat(persona_fd)
    if not stat.S_ISDIR(persona_st.st_mode):
        fail(f"{persona_dir} is not a directory")
    try:
        existing = os.stat("SOUL.md", dir_fd=persona_fd, follow_symlinks=False)
    except FileNotFoundError:
        existing = None
    if existing is not None:
        if stat.S_ISLNK(existing.st_mode):
            fail(f"{persona_dir}/SOUL.md is a symlink; refusing privileged QR1 provisioning")
        if stat.S_ISDIR(existing.st_mode):
            fail(f"{persona_dir}/SOUL.md is a directory, probably created by a previous failed Docker bind mount.")
        if not stat.S_ISREG(existing.st_mode):
            fail(f"{persona_dir}/SOUL.md is not a regular file")
    if race_mode:
        if not race_external:
            fail("MS_QR1_TEST_PERSONA_RACE_EXTERNAL is required for race fixture")
        if race_mode == "soul-symlink":
            try:
                os.rename("SOUL.md", "SOUL.md.race-original", src_dir_fd=persona_fd, dst_dir_fd=persona_fd)
            except FileNotFoundError:
                pass
            os.symlink(race_external, os.path.join(persona_dir, "SOUL.md"))
        elif race_mode == "persona-dir-swap":
            os.rename(persona_dir, f"{persona_dir}.race-original")
            os.symlink(race_external, persona_dir)
        else:
            fail(f"unknown persona race fixture {race_mode!r}")
    if os.geteuid() == 0:
        os.chown(soul_tmp, deploy_uid, deploy_gid, follow_symlinks=False)
    os.chmod(soul_tmp, 0o644, follow_symlinks=False)
    os.rename(soul_tmp, "SOUL.md", dst_dir_fd=persona_fd)
    final_st = os.stat("SOUL.md", dir_fd=persona_fd, follow_symlinks=False)
    if stat.S_ISLNK(final_st.st_mode) or not stat.S_ISREG(final_st.st_mode):
        fail(f"{persona_dir}/SOUL.md was not installed as a regular file")
finally:
    os.close(persona_fd)
PY
  rm -f "$soul_tmp"
  trap - RETURN
}

validate_or_normalize_n8n_tree() {
  N8N_DIR="$N8N_DIR" N8N_UID="$1" N8N_GID="$2" N8N_NORMALIZE="${3:-0}" python3 - <<'PY'
import errno
import os
import stat
import sys

root = os.environ["N8N_DIR"]
expected_uid = int(os.environ["N8N_UID"])
expected_gid = int(os.environ["N8N_GID"])
normalize = os.environ["N8N_NORMALIZE"] == "1"
force_chmod_not_implemented = os.environ.get("MS_QR1_TEST_CHMOD_NO_FOLLOW_UNSUPPORTED") == "1"
race_mode = os.environ.get("MS_QR1_TEST_N8N_RACE", "")
race_external = os.environ.get("MS_QR1_TEST_N8N_RACE_EXTERNAL", "")
running_as_root = os.geteuid() == 0
open_flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
dir_flags = open_flags | getattr(os, "O_DIRECTORY", 0)
race_fired = False

def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)

def desired_mode(path: str, st: os.stat_result) -> int:
    mode = stat.S_IMODE(st.st_mode)
    if stat.S_ISDIR(st.st_mode):
        return 0o700
    if stat.S_ISREG(st.st_mode):
        return 0o600 | (mode & stat.S_IXUSR)
    fail(f"{path} is neither a directory nor a regular file")

def same_object(left: os.stat_result, right: os.stat_result) -> bool:
    return (left.st_dev, left.st_ino) == (right.st_dev, right.st_ino)

def trigger_race(parent_display: str, name: str, phase: str) -> None:
    global race_fired
    if race_fired or not race_mode:
        return
    if not race_external:
        fail("MS_QR1_TEST_N8N_RACE_EXTERNAL is required for race fixture")
    parent_path = os.path.join(root, os.path.relpath(parent_display, root)) if parent_display != root else root
    if race_mode == "parent-swap" and parent_display == root and name == "nested" and phase == "before-open":
        os.rename(os.path.join(parent_path, name), os.path.join(parent_path, f"{name}.race-original"))
        os.symlink(race_external, os.path.join(parent_path, name))
        race_fired = True
    elif race_mode == "final-swap" and parent_display.endswith("/nested") and name == "blob" and phase == "before-open":
        os.rename(os.path.join(parent_path, name), os.path.join(parent_path, f"{name}.race-original"))
        os.symlink(race_external, os.path.join(parent_path, name))
        race_fired = True
    elif race_mode == "symlink-insert" and parent_display == root and phase == "before-rescan":
        os.symlink(race_external, os.path.join(parent_path, "inserted-race-link"))
        race_fired = True

def apply_or_check(fd: int, display: str, st: os.stat_result) -> None:
    desired = desired_mode(display, st)
    if (st.st_uid, st.st_gid) != (expected_uid, expected_gid):
        if not normalize or not running_as_root:
            fail(f"{display} owner is {st.st_uid}:{st.st_gid}, expected {expected_uid}:{expected_gid}")
        os.fchown(fd, expected_uid, expected_gid)
        st = os.fstat(fd)
    mode = stat.S_IMODE(st.st_mode)
    if normalize and mode != desired:
        try:
            if force_chmod_not_implemented:
                raise NotImplementedError("forced test path")
            os.fchmod(fd, desired)
        except NotImplementedError:
            fail(f"cannot chmod {display} without following symlinks on this Python/platform; use Ubuntu 24.04 or a Python build with follow_symlinks support")
        except PermissionError:
            fail(f"cannot chmod {display}; rerun provisioning with sudo")
        mode = stat.S_IMODE(os.fstat(fd).st_mode)
    if not normalize:
        if not mode & stat.S_IWUSR:
            fail(f"{display} is not owner-writable: {mode:04o}")
        if stat.S_ISDIR(st.st_mode) and not mode & stat.S_IXUSR:
            fail(f"{display} is not owner-searchable: {mode:04o}")
        if mode & stat.S_IWGRP:
            fail(f"{display} is group-writable: {mode:04o}")
        if mode & stat.S_IWOTH:
            fail(f"{display} is world-writable: {mode:04o}")
    elif mode != desired:
        fail(f"{display} mode is {mode:04o}, expected {desired:04o}")

def open_child(parent_fd: int, parent_display: str, name: str) -> tuple[int, os.stat_result]:
    display = os.path.join(parent_display, name)
    trigger_race(parent_display, name, "before-open")
    try:
        st = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        fail(f"{display} disappeared during traversal")
    if stat.S_ISLNK(st.st_mode):
        fail(f"{display} is a symlink; refusing privileged n8n provisioning")
    if not stat.S_ISDIR(st.st_mode) and not stat.S_ISREG(st.st_mode):
        fail(f"{display} is neither a directory nor a regular file")
    if not normalize and stat.S_ISDIR(st.st_mode):
        mode = stat.S_IMODE(st.st_mode)
        if (st.st_uid, st.st_gid) != (expected_uid, expected_gid):
            fail(f"{display} owner is {st.st_uid}:{st.st_gid}, expected {expected_uid}:{expected_gid}")
        if not mode & stat.S_IWUSR:
            fail(f"{display} is not owner-writable: {mode:04o}")
        if not mode & stat.S_IXUSR:
            fail(f"{display} is not owner-searchable: {mode:04o}")
        if mode & stat.S_IWGRP:
            fail(f"{display} is group-writable: {mode:04o}")
        if mode & stat.S_IWOTH:
            fail(f"{display} is world-writable: {mode:04o}")
    flags = dir_flags if stat.S_ISDIR(st.st_mode) else open_flags
    try:
        child_fd = os.open(name, flags, dir_fd=parent_fd)
    except OSError as exc:
        if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
            fail(f"{display} changed during traversal or is a symlink")
        if exc.errno == errno.ENOENT:
            fail(f"{display} disappeared during traversal")
        fail(f"cannot open {display} safely: {exc.strerror}")
    opened_st = os.fstat(child_fd)
    if not same_object(st, opened_st):
        os.close(child_fd)
        fail(f"{display} changed during traversal")
    return child_fd, opened_st

def visit_dir(dir_fd: int, display: str, st: os.stat_result) -> None:
    if not stat.S_ISDIR(st.st_mode):
        fail(f"{display} is not a directory")
    apply_or_check(dir_fd, display, st)
    try:
        names = sorted(os.listdir(dir_fd))
    except OSError as exc:
        fail(f"cannot list {display}: {exc.strerror}")
    for name in names:
        if name in {"", ".", ".."} or "/" in name or "\0" in name:
            fail(f"{display} contains invalid entry name {name!r}")
        child_fd, child_st = open_child(dir_fd, display, name)
        try:
            child_display = os.path.join(display, name)
            if stat.S_ISDIR(child_st.st_mode):
                visit_dir(child_fd, child_display, child_st)
            elif stat.S_ISREG(child_st.st_mode):
                apply_or_check(child_fd, child_display, child_st)
            else:
                fail(f"{child_display} is neither a directory nor a regular file")
        finally:
            os.close(child_fd)
    trigger_race(display, "", "before-rescan")
    try:
        after_names = sorted(os.listdir(dir_fd))
    except OSError as exc:
        fail(f"cannot relist {display}: {exc.strerror}")
    if after_names != names:
        fail(f"{display} changed during traversal")

try:
    root_fd = os.open(root, dir_flags)
except FileNotFoundError:
    fail(f"missing {root}")
except OSError as exc:
    if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
        fail(f"{root} is a symlink; refusing privileged n8n provisioning")
    fail(f"cannot open {root} safely: {exc.strerror}")
try:
    root_st = os.fstat(root_fd)
    visit_dir(root_fd, root, root_st)
finally:
    os.close(root_fd)
PY
}

ensure_n8n_dir() {
  local n8n_user n8n_uid n8n_gid
  n8n_user="$(resolve_n8n_user)"
  if [[ -z "$n8n_user" ]]; then
    echo "QR1 n8n service absent from rendered stack; skipping data/n8n provisioning"
    return 0
  fi
  n8n_uid="${n8n_user%%:*}"
  n8n_gid="${n8n_user##*:}"
  mkdir -p "$N8N_DIR"
  if ! validate_or_normalize_n8n_tree "$n8n_uid" "$n8n_gid" 1; then
    is_root || require_root "$N8N_DIR requires ownership or mode repair for $n8n_uid:$n8n_gid"
    return 1
  fi
  validate_or_normalize_n8n_tree "$n8n_uid" "$n8n_gid" 0
}

check_prestart() {
  validate_persona_paths
  python3 - "$SOUL_PATH" <<'PY'
from pathlib import Path
import sys

Path(sys.argv[1]).read_text(encoding="utf-8")
PY
  local n8n_user n8n_uid n8n_gid
  n8n_user="$(resolve_n8n_user)"
  if [[ -z "$n8n_user" ]]; then
    return 0
  fi
  [[ -d "$N8N_DIR" ]] || { echo "ERROR: missing $N8N_DIR" >&2; return 1; }
  n8n_uid="${n8n_user%%:*}"
  n8n_gid="${n8n_user##*:}"
  validate_or_normalize_n8n_tree "$n8n_uid" "$n8n_gid" 0
}

if [[ "$ACTION" == "n8n-user" ]]; then
  resolve_n8n_user
  exit 0
fi

if [[ "$ACTION" == "check" ]]; then
  check_prestart
  exit 0
fi

poststart_refresh() {
  ensure_persona
  require docker
  local containers
  containers="$(docker ps --format '{{.Names}}')"
  if ! grep -Fx 'ods-hermes' <<<"$containers" >/dev/null; then
    echo "ERROR: ods-hermes is not running; cannot refresh Hermes persona" >&2
    return 1
  fi
  docker exec ods-hermes cp /opt/hermes/docker/SOUL.md /opt/data/SOUL.md
}

if [[ "$ACTION" == "poststart-refresh" ]]; then
  poststart_refresh
  exit 0
fi

ensure_persona
ensure_n8n_dir
check_prestart
echo "QR1 pre-start provisioning complete"
