#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/ods-verify-quiescent-data-writers.sh writer-services --target PATH [--target PATH ...]
  scripts/ods-verify-quiescent-data-writers.sh writer-containers --target PATH [--target PATH ...]
  scripts/ods-verify-quiescent-data-writers.sh verify --target PATH [--target PATH ...]

Options:
  --install-dir DIR   ODS install/repository root. Defaults to current directory.
  --target PATH       Persistent data path to protect. May be relative to install dir.

Environment:
  ODS_QUIESCENCE_COMPOSE_FLAGS  Optional docker compose -f flags for the active deployment.
  ODS_QUIESCENCE_DATA_DIR       Optional data root for deployments that relocate ./data.

Read-only helper. It renders the active Compose model, derives services with
writable bind mounts intersecting the target path(s), and verifies those
containers are stopped before a separate privileged mutation helper proceeds.
USAGE
}

ACTION="${1:-}"
case "$ACTION" in
  writer-services|writer-containers|verify) shift ;;
  -h|--help|help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac

INSTALL_DIR="."
TARGETS=()
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --install-dir)
      [[ "$#" -ge 2 ]] || { echo "ERROR: --install-dir requires a value" >&2; exit 2; }
      INSTALL_DIR="$2"
      shift 2
      ;;
    --target)
      [[ "$#" -ge 2 ]] || { echo "ERROR: --target requires a value" >&2; exit 2; }
      TARGETS+=("$2")
      shift 2
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ "${#TARGETS[@]}" -gt 0 ]] || { echo "ERROR: at least one --target is required" >&2; exit 2; }
command -v docker >/dev/null || { echo "ERROR: docker is required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "ERROR: python3 is required" >&2; exit 1; }
[[ -d "$INSTALL_DIR" ]] || { echo "ERROR: install dir does not exist: $INSTALL_DIR" >&2; exit 1; }

compose_flags() {
  if [[ -n "${ODS_QUIESCENCE_COMPOSE_FLAGS:-}" ]]; then
    printf '%s\n' "$ODS_QUIESCENCE_COMPOSE_FLAGS"
  elif [[ -f "$INSTALL_DIR/.compose-flags" ]]; then
    cat "$INSTALL_DIR/.compose-flags"
  elif [[ -f "$INSTALL_DIR/docker-compose.yml" || -f "$INSTALL_DIR/compose.yaml" || -f "$INSTALL_DIR/compose.yml" ]]; then
    printf '\n'
  elif [[ -f "$INSTALL_DIR/docker-compose.base.yml" ]]; then
    printf -- '-f docker-compose.base.yml\n'
  else
    echo "ERROR: cannot determine active Compose files; set ODS_QUIESCENCE_COMPOSE_FLAGS" >&2
    return 1
  fi
}

render_compose_json() {
  local flags_string
  flags_string="$(compose_flags)"
  # Compose flags are generated by repo helpers or .compose-flags. Keep this
  # parser intentionally simple and avoid eval; paths with spaces are not a
  # supported compose-flag format elsewhere in ODS shell helpers either.
  read -r -a flags <<<"$flags_string"
  (cd "$INSTALL_DIR" && docker compose "${flags[@]}" config --format json)
}

TARGETS_PAYLOAD="$(printf '%s\n' "${TARGETS[@]}")"
COMPOSE_JSON="$(render_compose_json)"
WRITERS="$(COMPOSE_JSON="$COMPOSE_JSON" TARGETS_PAYLOAD="$TARGETS_PAYLOAD" INSTALL_DIR="$INSTALL_DIR" OUTPUT_KIND="$ACTION" DATA_DIR="${ODS_QUIESCENCE_DATA_DIR:-}" python3 - <<'PY'
import json
import os
from pathlib import Path

data = json.loads(os.environ["COMPOSE_JSON"])
install_dir = Path(os.environ["INSTALL_DIR"]).resolve()
data_dir_value = os.environ.get("DATA_DIR") or "data"
data_dir = Path(data_dir_value)
if not data_dir.is_absolute():
    data_dir = install_dir / data_dir
data_dir = data_dir.resolve()
target_lines = [line.strip() for line in os.environ["TARGETS_PAYLOAD"].splitlines() if line.strip()]
output_kind = os.environ["OUTPUT_KIND"]
targets = []
for target in target_lines:
    path = Path(target)
    if not path.is_absolute():
        path = install_dir / path
    targets.append(path.resolve())

def intersects(left, right):
    return left == right or left in right.parents or right in left.parents

def string_volume_source(volume):
    parts = volume.split(":")
    if len(parts) < 2:
        return None, False
    options = []
    for part in parts[2:]:
        options.extend(item.strip() for item in part.split(","))
    return parts[0], "ro" in options

writers = []
for service_name, service in sorted((data.get("services") or {}).items()):
    for volume in service.get("volumes") or []:
        source = None
        read_only = False
        if isinstance(volume, str):
            source, read_only = string_volume_source(volume)
        elif isinstance(volume, dict) and volume.get("type") == "bind":
            source = volume.get("source")
            read_only = bool(volume.get("read_only"))
        if not source or read_only:
            continue
        source_path = Path(str(source))
        if not source_path.is_absolute():
            parts = tuple(part for part in source_path.parts if part != ".")
            if parts and parts[0] == "data":
                source_path = data_dir.joinpath(*parts[1:])
            else:
                source_path = install_dir / source_path
        try:
            source_abs = source_path.resolve()
        except OSError:
            source_abs = source_path.absolute()
        if any(intersects(source_abs, target) for target in targets):
            if output_kind == "writer-services":
                writers.append(service_name)
            else:
                writers.append(str(service.get("container_name") or f"ods-{service_name}"))
            break

for writer in sorted(set(writers)):
    print(writer)
PY
)"

if [[ "$ACTION" == "writer-services" || "$ACTION" == "writer-containers" ]]; then
  printf '%s\n' "$WRITERS" | sed '/^$/d'
  exit 0
fi

[[ -n "$WRITERS" ]] || exit 0
RUNNING="$(docker ps --format '{{.Names}}')"
ACTIVE="$(EXPECTED_WRITERS="$WRITERS" RUNNING_CONTAINERS="$RUNNING" python3 - <<'PY'
import os

expected = set(filter(None, os.environ["EXPECTED_WRITERS"].splitlines()))
running = set(filter(None, os.environ["RUNNING_CONTAINERS"].splitlines()))
for name in sorted(expected & running):
    print(name)
PY
)"
if [[ -n "$ACTIVE" ]]; then
  echo "ERROR: privileged persistent-state mutation requires quiescent container-writable state." >&2
  echo "Stop these writer container(s) before repair:" >&2
  printf '  %s\n' $ACTIVE >&2
  return_code=1
else
  return_code=0
fi
exit "$return_code"
